名字: 生成和部署Windows可执行文件


#on:
  #schedule:
   #-cron：'018******'#早上 2
  #push:
    #branches:
      #-主要

工作:
  build-and-deploy:
    runs-on: windows-latest

步骤:
      - 名字: 签出库
用途: actions/checkout@v2

      - 名字: Python
用途: actions/setup-python@v2
与:
          python-version: 3.x

      - 名字: 安装依赖项
跑: pip installer selenium请求期货eventlet

      - 名字: 构建可执行文件
跑: pyinstaller IPTV-hebei.py --onefile --hidden-import=eventlet.hubs.epolls --hidden-import=eventlet.hubs.kqueue --hidden-import=eventlet.hubs.selects --hidden-import=dns --hidden-import=dns.rdtypes --hidden-import=dns.rdtypes.ANY --hidden-import=dns.rdtypes.IN --hidden-import=dns.rdtypes.CH --hidden-import=dns.rdtypes.dnskeybase --hidden-import=dns.asyncbackend --hidden-import=dns.asyncquery --hidden-import=dns.asyncresolver --hidden-import=dns.dnssec --hidden-import=dns.e164 --hidden-import=dns.namedict --hidden-import=dns.tsigkeyring --hidden-import=dns.versioned
      - 跑: pyinstaller windows_test.py --onefile
      #- name: Create directory
      # run: mkdir -p windows
      - 名字: 删除现有文件
跑: rm windows/IPTV-hebei.exe
      - 跑: rm windows/windows_test.exe

      - 名字: 将可执行文件移到目录
跑: mv dist/IPTV-hebei.exe windows/
      - 跑: mv dist/windows_test.exe windows/

      - 名字: 提交更改
跑: |
git config--全局用户. name“181728”
git config --global user.email "1817281988@qq.com"
添加windows/IPTV-hebei.exe
git添加windows/windows_test.exe
git commit -m “更新Windows可执行文件”
git推送
